Update manifest.in, add missing file
otherwise build fails:

```
>>> Emerging (1 of 1) dev-python/gios-0.2.0::HomeAssistantRepository
>>> Failed to emerge dev-python/gios-0.2.0, Log file:
>>>  '/var/tmp/portage/dev-python/gios-0.2.0/temp/build.log'
>>> Jobs: 0 of 1 complete, 1 failed                 Load avg: 0.50, 0.58, 0.58
 * Package:    dev-python/gios-0.2.0
 * Repository: HomeAssistantRepository
 * Maintainer: b@edevau.net
 * Upstream:   maciej.bieniek@gmail.com
 * USE:        abi_x86_64 amd64 elibc_glibc kernel_linux python_targets_python3_8 test userland_GNU
 * FEATURES:   network-sandbox preserve-libs sandbox userpriv usersandbox
>>> Unpacking source...
>>> Unpacking gios-0.2.0.tar.gz to /var/tmp/portage/dev-python/gios-0.2.0/work
>>> Source unpacked in /var/tmp/portage/dev-python/gios-0.2.0/work
>>> Preparing source in /var/tmp/portage/dev-python/gios-0.2.0/work/gios-0.2.0 ...
>>> Source prepared.
>>> Configuring source in /var/tmp/portage/dev-python/gios-0.2.0/work/gios-0.2.0 ...
>>> Source configured.
>>> Compiling source in /var/tmp/portage/dev-python/gios-0.2.0/work/gios-0.2.0 ...
 * python3_8: running distutils-r1_run_phase distutils-r1_python_compile
python3.8 setup.py build -j 10
Traceback (most recent call last):
  File "setup.py", line 16, in <module>
    install_requires=list(val.strip() for val in open("requirements.txt")),
FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
 * ERROR: dev-python/gios-0.2.0::HomeAssistantRepository failed (compile phase):
 *   (no error message)
```